# Form implementation generated from reading ui file 'sinhhoatthang_redesigned.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SinhHoatThang(object):
    def setupUi(self, SinhHoatThang):
        SinhHoatThang.setObjectName("SinhHoatThang")
        SinhHoatThang.resize(900, 405)
        SinhHoatThang.setStyleSheet("QMainWindow {\n"
"    background-color: #F5F7FA;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 15px;\n"
"}\n"
"QWidget#centralwidget {\n"
"    background-color: #F5F7FA;\n"
"}\n"
"QFrame#frmDien,\n"
"QFrame#frmNuoc,\n"
"QFrame#frmRac {\n"
"    background-color: #FFFFFF; \n"
"    border: 1px solid #E0E0E0; \n"
"    border-radius: 8px; \n"
"}\n"
"QLabel {\n"
"    color: #333333; \n"
"    padding: 4px 0px; \n"
"}\n"
"QLabel#lblDien,\n"
"QLabel#lblNuoc,\n"
"QLabel#lblRac {\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    color: #000000;\n"
"    padding-bottom: 8px; \n"
"}\n"
"QLabel#lblRacPhi {\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    color: #1A2B4C; \n"
"}\n"
"QLineEdit,\n"
"QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #DCDCDC;\n"
"    border-radius: 5px; \n"
"    padding: 10px 12px;\n"
"    font-size: 10px;\n"
"    color: #333333;\n"
"}\n"
"QLineEdit[readOnly=\"true\"] {\n"
"    background-color: #F0F0F0;\n"
"    color: #777777;\n"
"    border: 1px solid #E0E0E0;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #E0E0E0;\n"
"    selection-background-color: #0078D7;\n"
"    selection-color: #FFFFFF;\n"
"    color: #333333;\n"
"    outline: 0px;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 10px 20px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;    \n"
"}\n"
"QPushButton#btnTinh {\n"
"    background-color: #0078D7; \n"
"    color: #FFFFFF;\n"
"}\n"
"QPushButton#btnClear {\n"
"    background-color: #E1E1E1;\n"
"    color: #333333;\n"
"    font-weight: normal;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=SinhHoatThang)
        self.centralwidget.setStyleSheet("QWidget#centralwidget {\n"
"    background-color: #F5F7FA;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(15, 15, 15, 15)
        self.mainLayout.setSpacing(15)
        self.mainLayout.setObjectName("mainLayout")
        self.lblTitle = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.mainLayout.addWidget(self.lblTitle)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.mainLayout.addWidget(self.label)
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")
        self.frmDien = QtWidgets.QFrame(parent=self.centralwidget)
        self.frmDien.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frmDien.setObjectName("frmDien")
        self.layoutDien = QtWidgets.QVBoxLayout(self.frmDien)
        self.layoutDien.setObjectName("layoutDien")
        self.lblDien = QtWidgets.QLabel(parent=self.frmDien)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDien.sizePolicy().hasHeightForWidth())
        self.lblDien.setSizePolicy(sizePolicy)
        self.lblDien.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.lblDien.setFont(font)
        self.lblDien.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblDien.setObjectName("lblDien")
        self.layoutDien.addWidget(self.lblDien)
        self.lneDienCu = QtWidgets.QLineEdit(parent=self.frmDien)
        self.lneDienCu.setObjectName("lneDienCu")
        self.layoutDien.addWidget(self.lneDienCu)
        self.lneDienMoi = QtWidgets.QLineEdit(parent=self.frmDien)
        self.lneDienMoi.setObjectName("lneDienMoi")
        self.layoutDien.addWidget(self.lneDienMoi)
        self.lneGiaDien = QtWidgets.QLineEdit(parent=self.frmDien)
        self.lneGiaDien.setText("")
        self.lneGiaDien.setReadOnly(True)
        self.lneGiaDien.setObjectName("lneGiaDien")
        self.layoutDien.addWidget(self.lneGiaDien)
        self.topLayout.addWidget(self.frmDien)
        self.frmNuoc = QtWidgets.QFrame(parent=self.centralwidget)
        self.frmNuoc.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frmNuoc.setObjectName("frmNuoc")
        self.layoutNuoc = QtWidgets.QVBoxLayout(self.frmNuoc)
        self.layoutNuoc.setObjectName("layoutNuoc")
        self.lblNuoc = QtWidgets.QLabel(parent=self.frmNuoc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNuoc.sizePolicy().hasHeightForWidth())
        self.lblNuoc.setSizePolicy(sizePolicy)
        self.lblNuoc.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.lblNuoc.setFont(font)
        self.lblNuoc.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblNuoc.setObjectName("lblNuoc")
        self.layoutNuoc.addWidget(self.lblNuoc)
        self.lneNuocCu = QtWidgets.QLineEdit(parent=self.frmNuoc)
        self.lneNuocCu.setObjectName("lneNuocCu")
        self.layoutNuoc.addWidget(self.lneNuocCu)
        self.lneNuocMoi = QtWidgets.QLineEdit(parent=self.frmNuoc)
        self.lneNuocMoi.setObjectName("lneNuocMoi")
        self.layoutNuoc.addWidget(self.lneNuocMoi)
        self.lneGiaNuoc = QtWidgets.QLineEdit(parent=self.frmNuoc)
        self.lneGiaNuoc.setText("")
        self.lneGiaNuoc.setReadOnly(True)
        self.lneGiaNuoc.setObjectName("lneGiaNuoc")
        self.layoutNuoc.addWidget(self.lneGiaNuoc)
        self.topLayout.addWidget(self.frmNuoc)
        self.frmRac = QtWidgets.QFrame(parent=self.centralwidget)
        self.frmRac.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frmRac.setObjectName("frmRac")
        self.layoutRac = QtWidgets.QVBoxLayout(self.frmRac)
        self.layoutRac.setObjectName("layoutRac")
        self.lblRac = QtWidgets.QLabel(parent=self.frmRac)
        self.lblRac.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.lblRac.setFont(font)
        self.lblRac.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblRac.setObjectName("lblRac")
        self.layoutRac.addWidget(self.lblRac)
        self.cmbKhuVuc = QtWidgets.QComboBox(parent=self.frmRac)
        self.cmbKhuVuc.setObjectName("cmbKhuVuc")
        self.layoutRac.addWidget(self.cmbKhuVuc)
        self.racPhiLayout = QtWidgets.QHBoxLayout()
        self.racPhiLayout.setObjectName("racPhiLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.racPhiLayout.addItem(spacerItem)
        self.lblRacPhi = QtWidgets.QLabel(parent=self.frmRac)
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.lblRacPhi.setFont(font)
        self.lblRacPhi.setObjectName("lblRacPhi")
        self.racPhiLayout.addWidget(self.lblRacPhi)
        self.layoutRac.addLayout(self.racPhiLayout)
        self.layoutRac.setStretch(0, 2)
        self.layoutRac.setStretch(1, 2)
        self.layoutRac.setStretch(2, 1)
        self.topLayout.addWidget(self.frmRac)
        self.topLayout.setStretch(0, 1)
        self.topLayout.setStretch(1, 1)
        self.topLayout.setStretch(2, 1)
        self.mainLayout.addLayout(self.topLayout)
        self.bottomLayout = QtWidgets.QHBoxLayout()
        self.bottomLayout.setObjectName("bottomLayout")
        self.btnTinh = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTinh.sizePolicy().hasHeightForWidth())
        self.btnTinh.setSizePolicy(sizePolicy)
        self.btnTinh.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.btnTinh.setFont(font)
        self.btnTinh.setObjectName("btnTinh")
        self.bottomLayout.addWidget(self.btnTinh)
        self.btnClear = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClear.sizePolicy().hasHeightForWidth())
        self.btnClear.setSizePolicy(sizePolicy)
        self.btnClear.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(False)
        font.setWeight(50)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.bottomLayout.addWidget(self.btnClear)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.bottomLayout.addItem(spacerItem1)
        self.lblTongPhi = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.lblTongPhi.setFont(font)
        self.lblTongPhi.setStyleSheet("QLabel#lblTongPhi {\n"
"    background-color: #E8F3FF;\n"
"    border: 1px solid #B4D7F8;\n"
"    border-radius: 6px;\n"
"    padding: 12px 18px;        \n"
"    color: #003366;\n"
"    font-size: 15px;  \n"
"    font-weight: bold;\n"
"    min-width: 180px;\n"
"}")
        self.lblTongPhi.setObjectName("lblTongPhi")
        self.bottomLayout.addWidget(self.lblTongPhi)
        self.bottomLayout.setStretch(0, 2)
        self.bottomLayout.setStretch(1, 2)
        self.bottomLayout.setStretch(2, 1)
        self.bottomLayout.setStretch(3, 2)
        self.mainLayout.addLayout(self.bottomLayout)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.mainLayout.addWidget(self.label_2)
        self.mainLayout.setStretch(2, 2)
        self.mainLayout.setStretch(3, 1)
        SinhHoatThang.setCentralWidget(self.centralwidget)

        self.retranslateUi(SinhHoatThang)
        QtCore.QMetaObject.connectSlotsByName(SinhHoatThang)

    def retranslateUi(self, SinhHoatThang):
        _translate = QtCore.QCoreApplication.translate
        SinhHoatThang.setWindowTitle(_translate("SinhHoatThang", "Tính phí sinh hoạt tháng"))
        self.lblTitle.setText(_translate("SinhHoatThang", "Tính tiền sinh hoạt hàng tháng"))
        self.label.setText(_translate("SinhHoatThang", "(Tại địa bàn TP.HCM)"))
        self.lblDien.setText(_translate("SinhHoatThang", "Điện (KWh) "))
        self.lneDienCu.setPlaceholderText(_translate("SinhHoatThang", "Chỉ số cũ"))
        self.lneDienMoi.setPlaceholderText(_translate("SinhHoatThang", "Chỉ số mới"))
        self.lneGiaDien.setPlaceholderText(_translate("SinhHoatThang", "0₫"))
        self.lblNuoc.setText(_translate("SinhHoatThang", "Nước (m³) "))
        self.lneNuocCu.setPlaceholderText(_translate("SinhHoatThang", "Chỉ số cũ"))
        self.lneNuocMoi.setPlaceholderText(_translate("SinhHoatThang", "Chỉ số mới"))
        self.lneGiaNuoc.setPlaceholderText(_translate("SinhHoatThang", "0₫"))
        self.lblRac.setText(_translate("SinhHoatThang", "Phí rác theo khu vực"))
        self.lblRacPhi.setText(_translate("SinhHoatThang", "Phí rác: 0 ₫"))
        self.btnTinh.setText(_translate("SinhHoatThang", "Tính"))
        self.btnClear.setText(_translate("SinhHoatThang", "Xóa"))
        self.lblTongPhi.setText(_translate("SinhHoatThang", "Tổng phí: 0 ₫"))
        self.label_2.setText(_translate("SinhHoatThang", "Dữ liệu được cập nhật đến ..."))
